version: "3.10.16"
services:
  clothing-model:
    image: zoomcamp-10-model:xception-v1-03
  gateway:
    image: zoomcamp-10-gateway
    # environment:
    #   - TF_SERVING_HOST=clothing-model:8500
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    depends_on:
      - clothing-model

networks:
  mynetwork:
    driver: bridge
